### ISSUE TITLE
memory and run time for large dataset

### ISSUE THREAD

**Issue by racng** [brianhie/scanorama#66] opened 2020-05-31 21:53 UTC
Hi, I am attempting to run scanorama on 150K cells from 40 samples on a c5.9xlarge EC2 instance with 32 cores and 64GB of RAM. Under this configuration scanorama fails with batch_size=1000 or 500. Now I am running it with batch_size=100 and RAM usage is at 40G. Processing each pair of datasets takes around 2 mins, and if there are 780 (40 choose 2) such pairs, I would expect this to finish in 26 hours. I saw the analysis of runtime and memory usage as a function of number cells in your publication. I was wondering if you have done analysis on time and memory usage as a function of number of datasets, each with around 3000 cells? Should I expect the run time to increase combinatorially with the number of dataset? Should I invest in more RAM or more CPUs for my EC2 instance?

Previously, I tested scanorama after downsampling this 40 samples dataset to 30K cells, and scanorama finished in an hour and produced a beautifully integrated umap. However my stdout only showed 570 lines of  "Processing datasets (i, j)". Should I have expected 780 (40 choose 2) such lines?

**Comment by brianhie** [comment] 2020-05-31 22:10
Hi @racng, sometimes Scanorama won't try to transform the values of two datasets, so it will be less than or equal to N choose 2 (where N is the number of datasets). Scalability will be with N choose 2, i.e., O(N^2) in the number of datasets.

In addition to batch size, you can also use the `sketch` parameter to the `integrate()` function and set the `sketch_max` parameter to get down to a total of 30k cells.  Scanorama will still integrate all cells, but only make alignments using the sketch. That will hopefully let you integrate without having to pay for more compute.

Will close the issue since it's not a bug with Scanorama, but am still happy to answer any additional questions.

**Closed by brianhie** 2020-05-31 22:10 UTC
